# Generated by Django 6.0 on 2025-12-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('area', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('owner', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(upload_to='site_images/')),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
